VALUE m_AvailabilityKind = rb_define_module_under(m_clang,"AvailabilityKind");
rb_define_const(m_AvailabilityKind,"Available", INT2NUM(0));
rb_define_const(m_AvailabilityKind,"Deprecated", INT2NUM(1));
rb_define_const(m_AvailabilityKind,"NotAvailable", INT2NUM(2));
rb_define_const(m_AvailabilityKind,"NotAccessible", INT2NUM(3));

VALUE m_GlobalOptFlags = rb_define_module_under(m_clang,"GlobalOptFlags");
rb_define_const(m_GlobalOptFlags,"None", INT2NUM(0));
rb_define_const(m_GlobalOptFlags,"ThreadBackgroundPriorityForIndexing", INT2NUM(1));
rb_define_const(m_GlobalOptFlags,"ThreadBackgroundPriorityForEditing", INT2NUM(2));
rb_define_const(m_GlobalOptFlags,"ThreadBackgroundPriorityForAll", INT2NUM(3));

VALUE m_DiagnosticSeverity = rb_define_module_under(m_clang,"DiagnosticSeverity");
rb_define_const(m_DiagnosticSeverity,"Ignored", INT2NUM(0));
rb_define_const(m_DiagnosticSeverity,"Note", INT2NUM(1));
rb_define_const(m_DiagnosticSeverity,"Warning", INT2NUM(2));
rb_define_const(m_DiagnosticSeverity,"Error", INT2NUM(3));
rb_define_const(m_DiagnosticSeverity,"Fatal", INT2NUM(4));

VALUE m_LoadDiag_Error = rb_define_module_under(m_clang,"LoadDiag_Error");
rb_define_const(m_LoadDiag_Error,"None", INT2NUM(0));
rb_define_const(m_LoadDiag_Error,"Unknown", INT2NUM(1));
rb_define_const(m_LoadDiag_Error,"CannotLoad", INT2NUM(2));
rb_define_const(m_LoadDiag_Error,"InvalidFile", INT2NUM(3));

VALUE m_DiagnosticDisplayOptions = rb_define_module_under(m_clang,"DiagnosticDisplayOptions");
rb_define_const(m_DiagnosticDisplayOptions,"DisplaySourceLocation", INT2NUM(1));
rb_define_const(m_DiagnosticDisplayOptions,"DisplayColumn", INT2NUM(2));
rb_define_const(m_DiagnosticDisplayOptions,"DisplaySourceRanges", INT2NUM(4));
rb_define_const(m_DiagnosticDisplayOptions,"DisplayOption", INT2NUM(8));
rb_define_const(m_DiagnosticDisplayOptions,"DisplayCategoryId", INT2NUM(16));
rb_define_const(m_DiagnosticDisplayOptions,"DisplayCategoryName", INT2NUM(32));

VALUE m_TranslationUnit_Flags = rb_define_module_under(m_clang,"TranslationUnit_Flags");
rb_define_const(m_TranslationUnit_Flags,"None", INT2NUM(0));
rb_define_const(m_TranslationUnit_Flags,"DetailedPreprocessingRecord", INT2NUM(1));
rb_define_const(m_TranslationUnit_Flags,"Incomplete", INT2NUM(2));
rb_define_const(m_TranslationUnit_Flags,"PrecompiledPreamble", INT2NUM(4));
rb_define_const(m_TranslationUnit_Flags,"CacheCompletionResults", INT2NUM(8));
rb_define_const(m_TranslationUnit_Flags,"ForSerialization", INT2NUM(16));
rb_define_const(m_TranslationUnit_Flags,"CXXChainedPCH", INT2NUM(32));
rb_define_const(m_TranslationUnit_Flags,"SkipFunctionBodies", INT2NUM(64));
rb_define_const(m_TranslationUnit_Flags,"IncludeBriefCommentsInCodeCompletion", INT2NUM(128));

VALUE m_SaveTranslationUnit_Flags = rb_define_module_under(m_clang,"SaveTranslationUnit_Flags");
rb_define_const(m_SaveTranslationUnit_Flags,"None", INT2NUM(0));

VALUE m_SaveError = rb_define_module_under(m_clang,"SaveError");
rb_define_const(m_SaveError,"None", INT2NUM(0));
rb_define_const(m_SaveError,"Unknown", INT2NUM(1));
rb_define_const(m_SaveError,"TranslationErrors", INT2NUM(2));
rb_define_const(m_SaveError,"InvalidTU", INT2NUM(3));

VALUE m_Reparse_Flags = rb_define_module_under(m_clang,"Reparse_Flags");
rb_define_const(m_Reparse_Flags,"None", INT2NUM(0));

VALUE m_TUResourceUsageKind = rb_define_module_under(m_clang,"TUResourceUsageKind");
rb_define_const(m_TUResourceUsageKind,"AST", INT2NUM(1));
rb_define_const(m_TUResourceUsageKind,"Identifiers", INT2NUM(2));
rb_define_const(m_TUResourceUsageKind,"Selectors", INT2NUM(3));
rb_define_const(m_TUResourceUsageKind,"GlobalCompletionResults", INT2NUM(4));
rb_define_const(m_TUResourceUsageKind,"SourceManagerContentCache", INT2NUM(5));
rb_define_const(m_TUResourceUsageKind,"AST_SideTables", INT2NUM(6));
rb_define_const(m_TUResourceUsageKind,"SourceManager_Membuffer_Malloc", INT2NUM(7));
rb_define_const(m_TUResourceUsageKind,"SourceManager_Membuffer_MMap", INT2NUM(8));
rb_define_const(m_TUResourceUsageKind,"ExternalASTSource_Membuffer_Malloc", INT2NUM(9));
rb_define_const(m_TUResourceUsageKind,"ExternalASTSource_Membuffer_MMap", INT2NUM(10));
rb_define_const(m_TUResourceUsageKind,"Preprocessor", INT2NUM(11));
rb_define_const(m_TUResourceUsageKind,"PreprocessingRecord", INT2NUM(12));
rb_define_const(m_TUResourceUsageKind,"SourceManager_DataStructures", INT2NUM(13));
rb_define_const(m_TUResourceUsageKind,"Preprocessor_HeaderSearch", INT2NUM(14));
rb_define_const(m_TUResourceUsageKind,"MEMORY_IN_BYTES_BEGIN", INT2NUM(1));
rb_define_const(m_TUResourceUsageKind,"MEMORY_IN_BYTES_END", INT2NUM(14));
rb_define_const(m_TUResourceUsageKind,"First", INT2NUM(1));
rb_define_const(m_TUResourceUsageKind,"Last", INT2NUM(14));

VALUE m_CursorKind = rb_define_module_under(m_clang,"CursorKind");
rb_define_const(m_CursorKind,"UnexposedDecl", INT2NUM(1));
rb_define_const(m_CursorKind,"StructDecl", INT2NUM(2));
rb_define_const(m_CursorKind,"UnionDecl", INT2NUM(3));
rb_define_const(m_CursorKind,"ClassDecl", INT2NUM(4));
rb_define_const(m_CursorKind,"EnumDecl", INT2NUM(5));
rb_define_const(m_CursorKind,"FieldDecl", INT2NUM(6));
rb_define_const(m_CursorKind,"EnumConstantDecl", INT2NUM(7));
rb_define_const(m_CursorKind,"FunctionDecl", INT2NUM(8));
rb_define_const(m_CursorKind,"VarDecl", INT2NUM(9));
rb_define_const(m_CursorKind,"ParmDecl", INT2NUM(10));
rb_define_const(m_CursorKind,"ObjCInterfaceDecl", INT2NUM(11));
rb_define_const(m_CursorKind,"ObjCCategoryDecl", INT2NUM(12));
rb_define_const(m_CursorKind,"ObjCProtocolDecl", INT2NUM(13));
rb_define_const(m_CursorKind,"ObjCPropertyDecl", INT2NUM(14));
rb_define_const(m_CursorKind,"ObjCIvarDecl", INT2NUM(15));
rb_define_const(m_CursorKind,"ObjCInstanceMethodDecl", INT2NUM(16));
rb_define_const(m_CursorKind,"ObjCClassMethodDecl", INT2NUM(17));
rb_define_const(m_CursorKind,"ObjCImplementationDecl", INT2NUM(18));
rb_define_const(m_CursorKind,"ObjCCategoryImplDecl", INT2NUM(19));
rb_define_const(m_CursorKind,"TypedefDecl", INT2NUM(20));
rb_define_const(m_CursorKind,"CXXMethod", INT2NUM(21));
rb_define_const(m_CursorKind,"Namespace", INT2NUM(22));
rb_define_const(m_CursorKind,"LinkageSpec", INT2NUM(23));
rb_define_const(m_CursorKind,"Constructor", INT2NUM(24));
rb_define_const(m_CursorKind,"Destructor", INT2NUM(25));
rb_define_const(m_CursorKind,"ConversionFunction", INT2NUM(26));
rb_define_const(m_CursorKind,"TemplateTypeParameter", INT2NUM(27));
rb_define_const(m_CursorKind,"NonTypeTemplateParameter", INT2NUM(28));
rb_define_const(m_CursorKind,"TemplateTemplateParameter", INT2NUM(29));
rb_define_const(m_CursorKind,"FunctionTemplate", INT2NUM(30));
rb_define_const(m_CursorKind,"ClassTemplate", INT2NUM(31));
rb_define_const(m_CursorKind,"ClassTemplatePartialSpecialization", INT2NUM(32));
rb_define_const(m_CursorKind,"NamespaceAlias", INT2NUM(33));
rb_define_const(m_CursorKind,"UsingDirective", INT2NUM(34));
rb_define_const(m_CursorKind,"UsingDeclaration", INT2NUM(35));
rb_define_const(m_CursorKind,"TypeAliasDecl", INT2NUM(36));
rb_define_const(m_CursorKind,"ObjCSynthesizeDecl", INT2NUM(37));
rb_define_const(m_CursorKind,"ObjCDynamicDecl", INT2NUM(38));
rb_define_const(m_CursorKind,"CXXAccessSpecifier", INT2NUM(39));
rb_define_const(m_CursorKind,"FirstDecl", INT2NUM(1));
rb_define_const(m_CursorKind,"LastDecl", INT2NUM(39));
rb_define_const(m_CursorKind,"FirstRef", INT2NUM(40));
rb_define_const(m_CursorKind,"ObjCSuperClassRef", INT2NUM(40));
rb_define_const(m_CursorKind,"ObjCProtocolRef", INT2NUM(41));
rb_define_const(m_CursorKind,"ObjCClassRef", INT2NUM(42));
rb_define_const(m_CursorKind,"TypeRef", INT2NUM(43));
rb_define_const(m_CursorKind,"CXXBaseSpecifier", INT2NUM(44));
rb_define_const(m_CursorKind,"TemplateRef", INT2NUM(45));
rb_define_const(m_CursorKind,"NamespaceRef", INT2NUM(46));
rb_define_const(m_CursorKind,"MemberRef", INT2NUM(47));
rb_define_const(m_CursorKind,"LabelRef", INT2NUM(48));
rb_define_const(m_CursorKind,"OverloadedDeclRef", INT2NUM(49));
rb_define_const(m_CursorKind,"VariableRef", INT2NUM(50));
rb_define_const(m_CursorKind,"LastRef", INT2NUM(50));
rb_define_const(m_CursorKind,"FirstInvalid", INT2NUM(70));
rb_define_const(m_CursorKind,"InvalidFile", INT2NUM(70));
rb_define_const(m_CursorKind,"NoDeclFound", INT2NUM(71));
rb_define_const(m_CursorKind,"NotImplemented", INT2NUM(72));
rb_define_const(m_CursorKind,"InvalidCode", INT2NUM(73));
rb_define_const(m_CursorKind,"LastInvalid", INT2NUM(73));
rb_define_const(m_CursorKind,"FirstExpr", INT2NUM(100));
rb_define_const(m_CursorKind,"UnexposedExpr", INT2NUM(100));
rb_define_const(m_CursorKind,"DeclRefExpr", INT2NUM(101));
rb_define_const(m_CursorKind,"MemberRefExpr", INT2NUM(102));
rb_define_const(m_CursorKind,"CallExpr", INT2NUM(103));
rb_define_const(m_CursorKind,"ObjCMessageExpr", INT2NUM(104));
rb_define_const(m_CursorKind,"BlockExpr", INT2NUM(105));
rb_define_const(m_CursorKind,"IntegerLiteral", INT2NUM(106));
rb_define_const(m_CursorKind,"FloatingLiteral", INT2NUM(107));
rb_define_const(m_CursorKind,"ImaginaryLiteral", INT2NUM(108));
rb_define_const(m_CursorKind,"StringLiteral", INT2NUM(109));
rb_define_const(m_CursorKind,"CharacterLiteral", INT2NUM(110));
rb_define_const(m_CursorKind,"ParenExpr", INT2NUM(111));
rb_define_const(m_CursorKind,"UnaryOperator", INT2NUM(112));
rb_define_const(m_CursorKind,"ArraySubscriptExpr", INT2NUM(113));
rb_define_const(m_CursorKind,"BinaryOperator", INT2NUM(114));
rb_define_const(m_CursorKind,"CompoundAssignOperator", INT2NUM(115));
rb_define_const(m_CursorKind,"ConditionalOperator", INT2NUM(116));
rb_define_const(m_CursorKind,"CStyleCastExpr", INT2NUM(117));
rb_define_const(m_CursorKind,"CompoundLiteralExpr", INT2NUM(118));
rb_define_const(m_CursorKind,"InitListExpr", INT2NUM(119));
rb_define_const(m_CursorKind,"AddrLabelExpr", INT2NUM(120));
rb_define_const(m_CursorKind,"StmtExpr", INT2NUM(121));
rb_define_const(m_CursorKind,"GenericSelectionExpr", INT2NUM(122));
rb_define_const(m_CursorKind,"GNUNullExpr", INT2NUM(123));
rb_define_const(m_CursorKind,"CXXStaticCastExpr", INT2NUM(124));
rb_define_const(m_CursorKind,"CXXDynamicCastExpr", INT2NUM(125));
rb_define_const(m_CursorKind,"CXXReinterpretCastExpr", INT2NUM(126));
rb_define_const(m_CursorKind,"CXXConstCastExpr", INT2NUM(127));
rb_define_const(m_CursorKind,"CXXFunctionalCastExpr", INT2NUM(128));
rb_define_const(m_CursorKind,"CXXTypeidExpr", INT2NUM(129));
rb_define_const(m_CursorKind,"CXXBoolLiteralExpr", INT2NUM(130));
rb_define_const(m_CursorKind,"CXXNullPtrLiteralExpr", INT2NUM(131));
rb_define_const(m_CursorKind,"CXXThisExpr", INT2NUM(132));
rb_define_const(m_CursorKind,"CXXThrowExpr", INT2NUM(133));
rb_define_const(m_CursorKind,"CXXNewExpr", INT2NUM(134));
rb_define_const(m_CursorKind,"CXXDeleteExpr", INT2NUM(135));
rb_define_const(m_CursorKind,"UnaryExpr", INT2NUM(136));
rb_define_const(m_CursorKind,"ObjCStringLiteral", INT2NUM(137));
rb_define_const(m_CursorKind,"ObjCEncodeExpr", INT2NUM(138));
rb_define_const(m_CursorKind,"ObjCSelectorExpr", INT2NUM(139));
rb_define_const(m_CursorKind,"ObjCProtocolExpr", INT2NUM(140));
rb_define_const(m_CursorKind,"ObjCBridgedCastExpr", INT2NUM(141));
rb_define_const(m_CursorKind,"PackExpansionExpr", INT2NUM(142));
rb_define_const(m_CursorKind,"SizeOfPackExpr", INT2NUM(143));
rb_define_const(m_CursorKind,"LambdaExpr", INT2NUM(144));
rb_define_const(m_CursorKind,"ObjCBoolLiteralExpr", INT2NUM(145));
rb_define_const(m_CursorKind,"ObjCSelfExpr", INT2NUM(146));
rb_define_const(m_CursorKind,"LastExpr", INT2NUM(146));
rb_define_const(m_CursorKind,"FirstStmt", INT2NUM(200));
rb_define_const(m_CursorKind,"UnexposedStmt", INT2NUM(200));
rb_define_const(m_CursorKind,"LabelStmt", INT2NUM(201));
rb_define_const(m_CursorKind,"CompoundStmt", INT2NUM(202));
rb_define_const(m_CursorKind,"CaseStmt", INT2NUM(203));
rb_define_const(m_CursorKind,"DefaultStmt", INT2NUM(204));
rb_define_const(m_CursorKind,"IfStmt", INT2NUM(205));
rb_define_const(m_CursorKind,"SwitchStmt", INT2NUM(206));
rb_define_const(m_CursorKind,"WhileStmt", INT2NUM(207));
rb_define_const(m_CursorKind,"DoStmt", INT2NUM(208));
rb_define_const(m_CursorKind,"ForStmt", INT2NUM(209));
rb_define_const(m_CursorKind,"GotoStmt", INT2NUM(210));
rb_define_const(m_CursorKind,"IndirectGotoStmt", INT2NUM(211));
rb_define_const(m_CursorKind,"ContinueStmt", INT2NUM(212));
rb_define_const(m_CursorKind,"BreakStmt", INT2NUM(213));
rb_define_const(m_CursorKind,"ReturnStmt", INT2NUM(214));
rb_define_const(m_CursorKind,"GCCAsmStmt", INT2NUM(215));
rb_define_const(m_CursorKind,"AsmStmt", INT2NUM(215));
rb_define_const(m_CursorKind,"ObjCAtTryStmt", INT2NUM(216));
rb_define_const(m_CursorKind,"ObjCAtCatchStmt", INT2NUM(217));
rb_define_const(m_CursorKind,"ObjCAtFinallyStmt", INT2NUM(218));
rb_define_const(m_CursorKind,"ObjCAtThrowStmt", INT2NUM(219));
rb_define_const(m_CursorKind,"ObjCAtSynchronizedStmt", INT2NUM(220));
rb_define_const(m_CursorKind,"ObjCAutoreleasePoolStmt", INT2NUM(221));
rb_define_const(m_CursorKind,"ObjCForCollectionStmt", INT2NUM(222));
rb_define_const(m_CursorKind,"CXXCatchStmt", INT2NUM(223));
rb_define_const(m_CursorKind,"CXXTryStmt", INT2NUM(224));
rb_define_const(m_CursorKind,"CXXForRangeStmt", INT2NUM(225));
rb_define_const(m_CursorKind,"SEHTryStmt", INT2NUM(226));
rb_define_const(m_CursorKind,"SEHExceptStmt", INT2NUM(227));
rb_define_const(m_CursorKind,"SEHFinallyStmt", INT2NUM(228));
rb_define_const(m_CursorKind,"MSAsmStmt", INT2NUM(229));
rb_define_const(m_CursorKind,"NullStmt", INT2NUM(230));
rb_define_const(m_CursorKind,"DeclStmt", INT2NUM(231));
rb_define_const(m_CursorKind,"OMPParallelDirective", INT2NUM(232));
rb_define_const(m_CursorKind,"OMPSimdDirective", INT2NUM(233));
rb_define_const(m_CursorKind,"OMPForDirective", INT2NUM(234));
rb_define_const(m_CursorKind,"OMPSectionsDirective", INT2NUM(235));
rb_define_const(m_CursorKind,"OMPSectionDirective", INT2NUM(236));
rb_define_const(m_CursorKind,"OMPSingleDirective", INT2NUM(237));
rb_define_const(m_CursorKind,"OMPParallelForDirective", INT2NUM(238));
rb_define_const(m_CursorKind,"OMPParallelSectionsDirective", INT2NUM(239));
rb_define_const(m_CursorKind,"OMPTaskDirective", INT2NUM(240));
rb_define_const(m_CursorKind,"OMPMasterDirective", INT2NUM(241));
rb_define_const(m_CursorKind,"OMPCriticalDirective", INT2NUM(242));
rb_define_const(m_CursorKind,"OMPTaskyieldDirective", INT2NUM(243));
rb_define_const(m_CursorKind,"OMPBarrierDirective", INT2NUM(244));
rb_define_const(m_CursorKind,"OMPTaskwaitDirective", INT2NUM(245));
rb_define_const(m_CursorKind,"OMPFlushDirective", INT2NUM(246));
rb_define_const(m_CursorKind,"SEHLeaveStmt", INT2NUM(247));
rb_define_const(m_CursorKind,"OMPOrderedDirective", INT2NUM(248));
rb_define_const(m_CursorKind,"OMPAtomicDirective", INT2NUM(249));
rb_define_const(m_CursorKind,"OMPForSimdDirective", INT2NUM(250));
rb_define_const(m_CursorKind,"OMPParallelForSimdDirective", INT2NUM(251));
rb_define_const(m_CursorKind,"OMPTargetDirective", INT2NUM(252));
rb_define_const(m_CursorKind,"OMPTeamsDirective", INT2NUM(253));
rb_define_const(m_CursorKind,"LastStmt", INT2NUM(253));
rb_define_const(m_CursorKind,"TranslationUnit", INT2NUM(300));
rb_define_const(m_CursorKind,"FirstAttr", INT2NUM(400));
rb_define_const(m_CursorKind,"UnexposedAttr", INT2NUM(400));
rb_define_const(m_CursorKind,"IBActionAttr", INT2NUM(401));
rb_define_const(m_CursorKind,"IBOutletAttr", INT2NUM(402));
rb_define_const(m_CursorKind,"IBOutletCollectionAttr", INT2NUM(403));
rb_define_const(m_CursorKind,"CXXFinalAttr", INT2NUM(404));
rb_define_const(m_CursorKind,"CXXOverrideAttr", INT2NUM(405));
rb_define_const(m_CursorKind,"AnnotateAttr", INT2NUM(406));
rb_define_const(m_CursorKind,"AsmLabelAttr", INT2NUM(407));
rb_define_const(m_CursorKind,"PackedAttr", INT2NUM(408));
rb_define_const(m_CursorKind,"PureAttr", INT2NUM(409));
rb_define_const(m_CursorKind,"ConstAttr", INT2NUM(410));
rb_define_const(m_CursorKind,"NoDuplicateAttr", INT2NUM(411));
rb_define_const(m_CursorKind,"CUDAConstantAttr", INT2NUM(412));
rb_define_const(m_CursorKind,"CUDADeviceAttr", INT2NUM(413));
rb_define_const(m_CursorKind,"CUDAGlobalAttr", INT2NUM(414));
rb_define_const(m_CursorKind,"CUDAHostAttr", INT2NUM(415));
rb_define_const(m_CursorKind,"CUDASharedAttr", INT2NUM(416));
rb_define_const(m_CursorKind,"LastAttr", INT2NUM(416));
rb_define_const(m_CursorKind,"PreprocessingDirective", INT2NUM(500));
rb_define_const(m_CursorKind,"MacroDefinition", INT2NUM(501));
rb_define_const(m_CursorKind,"MacroExpansion", INT2NUM(502));
rb_define_const(m_CursorKind,"MacroInstantiation", INT2NUM(502));
rb_define_const(m_CursorKind,"InclusionDirective", INT2NUM(503));
rb_define_const(m_CursorKind,"FirstPreprocessing", INT2NUM(500));
rb_define_const(m_CursorKind,"LastPreprocessing", INT2NUM(503));
rb_define_const(m_CursorKind,"ModuleImportDecl", INT2NUM(600));
rb_define_const(m_CursorKind,"FirstExtraDecl", INT2NUM(600));
rb_define_const(m_CursorKind,"LastExtraDecl", INT2NUM(600));

VALUE m_LinkageKind = rb_define_module_under(m_clang,"LinkageKind");
rb_define_const(m_LinkageKind,"Invalid", INT2NUM(0));
rb_define_const(m_LinkageKind,"NoLinkage", INT2NUM(1));
rb_define_const(m_LinkageKind,"Internal", INT2NUM(2));
rb_define_const(m_LinkageKind,"UniqueExternal", INT2NUM(3));
rb_define_const(m_LinkageKind,"External", INT2NUM(4));

VALUE m_LanguageKind = rb_define_module_under(m_clang,"LanguageKind");
rb_define_const(m_LanguageKind,"Invalid", INT2NUM(0));
rb_define_const(m_LanguageKind,"C", INT2NUM(1));
rb_define_const(m_LanguageKind,"ObjC", INT2NUM(2));
rb_define_const(m_LanguageKind,"CPlusPlus", INT2NUM(3));

VALUE m_TypeKind = rb_define_module_under(m_clang,"TypeKind");
rb_define_const(m_TypeKind,"Invalid", INT2NUM(0));
rb_define_const(m_TypeKind,"Unexposed", INT2NUM(1));
rb_define_const(m_TypeKind,"Void", INT2NUM(2));
rb_define_const(m_TypeKind,"Bool", INT2NUM(3));
rb_define_const(m_TypeKind,"Char_U", INT2NUM(4));
rb_define_const(m_TypeKind,"UChar", INT2NUM(5));
rb_define_const(m_TypeKind,"Char16", INT2NUM(6));
rb_define_const(m_TypeKind,"Char32", INT2NUM(7));
rb_define_const(m_TypeKind,"UShort", INT2NUM(8));
rb_define_const(m_TypeKind,"UInt", INT2NUM(9));
rb_define_const(m_TypeKind,"ULong", INT2NUM(10));
rb_define_const(m_TypeKind,"ULongLong", INT2NUM(11));
rb_define_const(m_TypeKind,"UInt128", INT2NUM(12));
rb_define_const(m_TypeKind,"Char_S", INT2NUM(13));
rb_define_const(m_TypeKind,"SChar", INT2NUM(14));
rb_define_const(m_TypeKind,"WChar", INT2NUM(15));
rb_define_const(m_TypeKind,"Short", INT2NUM(16));
rb_define_const(m_TypeKind,"Int", INT2NUM(17));
rb_define_const(m_TypeKind,"Long", INT2NUM(18));
rb_define_const(m_TypeKind,"LongLong", INT2NUM(19));
rb_define_const(m_TypeKind,"Int128", INT2NUM(20));
rb_define_const(m_TypeKind,"Float", INT2NUM(21));
rb_define_const(m_TypeKind,"Double", INT2NUM(22));
rb_define_const(m_TypeKind,"LongDouble", INT2NUM(23));
rb_define_const(m_TypeKind,"NullPtr", INT2NUM(24));
rb_define_const(m_TypeKind,"Overload", INT2NUM(25));
rb_define_const(m_TypeKind,"Dependent", INT2NUM(26));
rb_define_const(m_TypeKind,"ObjCId", INT2NUM(27));
rb_define_const(m_TypeKind,"ObjCClass", INT2NUM(28));
rb_define_const(m_TypeKind,"ObjCSel", INT2NUM(29));
rb_define_const(m_TypeKind,"FirstBuiltin", INT2NUM(2));
rb_define_const(m_TypeKind,"LastBuiltin", INT2NUM(29));
rb_define_const(m_TypeKind,"Complex", INT2NUM(100));
rb_define_const(m_TypeKind,"Pointer", INT2NUM(101));
rb_define_const(m_TypeKind,"BlockPointer", INT2NUM(102));
rb_define_const(m_TypeKind,"LValueReference", INT2NUM(103));
rb_define_const(m_TypeKind,"RValueReference", INT2NUM(104));
rb_define_const(m_TypeKind,"Record", INT2NUM(105));
rb_define_const(m_TypeKind,"Enum", INT2NUM(106));
rb_define_const(m_TypeKind,"Typedef", INT2NUM(107));
rb_define_const(m_TypeKind,"ObjCInterface", INT2NUM(108));
rb_define_const(m_TypeKind,"ObjCObjectPointer", INT2NUM(109));
rb_define_const(m_TypeKind,"FunctionNoProto", INT2NUM(110));
rb_define_const(m_TypeKind,"FunctionProto", INT2NUM(111));
rb_define_const(m_TypeKind,"ConstantArray", INT2NUM(112));
rb_define_const(m_TypeKind,"Vector", INT2NUM(113));
rb_define_const(m_TypeKind,"IncompleteArray", INT2NUM(114));
rb_define_const(m_TypeKind,"VariableArray", INT2NUM(115));
rb_define_const(m_TypeKind,"DependentSizedArray", INT2NUM(116));
rb_define_const(m_TypeKind,"MemberPointer", INT2NUM(117));

VALUE m_CallingConv = rb_define_module_under(m_clang,"CallingConv");
rb_define_const(m_CallingConv,"Default", INT2NUM(0));
rb_define_const(m_CallingConv,"C", INT2NUM(1));
rb_define_const(m_CallingConv,"X86StdCall", INT2NUM(2));
rb_define_const(m_CallingConv,"X86FastCall", INT2NUM(3));
rb_define_const(m_CallingConv,"X86ThisCall", INT2NUM(4));
rb_define_const(m_CallingConv,"X86Pascal", INT2NUM(5));
rb_define_const(m_CallingConv,"AAPCS", INT2NUM(6));
rb_define_const(m_CallingConv,"AAPCS_VFP", INT2NUM(7));
rb_define_const(m_CallingConv,"PnaclCall", INT2NUM(8));
rb_define_const(m_CallingConv,"IntelOclBicc", INT2NUM(9));
rb_define_const(m_CallingConv,"X86_64Win64", INT2NUM(10));
rb_define_const(m_CallingConv,"X86_64SysV", INT2NUM(11));
rb_define_const(m_CallingConv,"X86VectorCall", INT2NUM(12));
rb_define_const(m_CallingConv,"Invalid", INT2NUM(100));
rb_define_const(m_CallingConv,"Unexposed", INT2NUM(200));

VALUE m_TemplateArgumentKind = rb_define_module_under(m_clang,"TemplateArgumentKind");
rb_define_const(m_TemplateArgumentKind,"Null", INT2NUM(0));
rb_define_const(m_TemplateArgumentKind,"Type", INT2NUM(1));
rb_define_const(m_TemplateArgumentKind,"Declaration", INT2NUM(2));
rb_define_const(m_TemplateArgumentKind,"NullPtr", INT2NUM(3));
rb_define_const(m_TemplateArgumentKind,"Integral", INT2NUM(4));
rb_define_const(m_TemplateArgumentKind,"Template", INT2NUM(5));
rb_define_const(m_TemplateArgumentKind,"TemplateExpansion", INT2NUM(6));
rb_define_const(m_TemplateArgumentKind,"Expression", INT2NUM(7));
rb_define_const(m_TemplateArgumentKind,"Pack", INT2NUM(8));
rb_define_const(m_TemplateArgumentKind,"Invalid", INT2NUM(9));

VALUE m_TypeLayoutError = rb_define_module_under(m_clang,"TypeLayoutError");
rb_define_const(m_TypeLayoutError,"Invalid", INT2NUM(-1));
rb_define_const(m_TypeLayoutError,"Incomplete", INT2NUM(-2));
rb_define_const(m_TypeLayoutError,"Dependent", INT2NUM(-3));
rb_define_const(m_TypeLayoutError,"NotConstantSize", INT2NUM(-4));
rb_define_const(m_TypeLayoutError,"InvalidFieldName", INT2NUM(-5));

VALUE m_RefQualifierKind = rb_define_module_under(m_clang,"RefQualifierKind");
rb_define_const(m_RefQualifierKind,"None", INT2NUM(0));
rb_define_const(m_RefQualifierKind,"LValue", INT2NUM(1));
rb_define_const(m_RefQualifierKind,"RValue", INT2NUM(2));

VALUE m__XAccessSpecifier = rb_define_module_under(m_clang,"_XAccessSpecifier");
rb_define_const(m__XAccessSpecifier,"CXXInvalidAccessSpecifier", INT2NUM(0));
rb_define_const(m__XAccessSpecifier,"CXXPublic", INT2NUM(1));
rb_define_const(m__XAccessSpecifier,"CXXProtected", INT2NUM(2));
rb_define_const(m__XAccessSpecifier,"CXXPrivate", INT2NUM(3));

VALUE m__StorageClass = rb_define_module_under(m_clang,"_StorageClass");
rb_define_const(m__StorageClass,"SC_Invalid", INT2NUM(0));
rb_define_const(m__StorageClass,"SC_None", INT2NUM(1));
rb_define_const(m__StorageClass,"SC_Extern", INT2NUM(2));
rb_define_const(m__StorageClass,"SC_Static", INT2NUM(3));
rb_define_const(m__StorageClass,"SC_PrivateExtern", INT2NUM(4));
rb_define_const(m__StorageClass,"SC_OpenCLWorkGroupLocal", INT2NUM(5));
rb_define_const(m__StorageClass,"SC_Auto", INT2NUM(6));
rb_define_const(m__StorageClass,"SC_Register", INT2NUM(7));

VALUE m_ChildVisitResult = rb_define_module_under(m_clang,"ChildVisitResult");
rb_define_const(m_ChildVisitResult,"Break", INT2NUM(0));
rb_define_const(m_ChildVisitResult,"Continue", INT2NUM(1));
rb_define_const(m_ChildVisitResult,"Recurse", INT2NUM(2));

VALUE m_ObjCPropertyAttrKind = rb_define_module_under(m_clang,"ObjCPropertyAttrKind");
rb_define_const(m_ObjCPropertyAttrKind,"noattr", INT2NUM(0));
rb_define_const(m_ObjCPropertyAttrKind,"readonly", INT2NUM(1));
rb_define_const(m_ObjCPropertyAttrKind,"getter", INT2NUM(2));
rb_define_const(m_ObjCPropertyAttrKind,"assign", INT2NUM(4));
rb_define_const(m_ObjCPropertyAttrKind,"readwrite", INT2NUM(8));
rb_define_const(m_ObjCPropertyAttrKind,"retain", INT2NUM(16));
rb_define_const(m_ObjCPropertyAttrKind,"copy", INT2NUM(32));
rb_define_const(m_ObjCPropertyAttrKind,"nonatomic", INT2NUM(64));
rb_define_const(m_ObjCPropertyAttrKind,"setter", INT2NUM(128));
rb_define_const(m_ObjCPropertyAttrKind,"atomic", INT2NUM(256));
rb_define_const(m_ObjCPropertyAttrKind,"weak", INT2NUM(512));
rb_define_const(m_ObjCPropertyAttrKind,"strong", INT2NUM(1024));
rb_define_const(m_ObjCPropertyAttrKind,"unsafe_unretained", INT2NUM(2048));

VALUE m_ObjCDeclQualifierKind = rb_define_module_under(m_clang,"ObjCDeclQualifierKind");
rb_define_const(m_ObjCDeclQualifierKind,"None", INT2NUM(0));
rb_define_const(m_ObjCDeclQualifierKind,"In", INT2NUM(1));
rb_define_const(m_ObjCDeclQualifierKind,"Inout", INT2NUM(2));
rb_define_const(m_ObjCDeclQualifierKind,"Out", INT2NUM(4));
rb_define_const(m_ObjCDeclQualifierKind,"Bycopy", INT2NUM(8));
rb_define_const(m_ObjCDeclQualifierKind,"Byref", INT2NUM(16));
rb_define_const(m_ObjCDeclQualifierKind,"Oneway", INT2NUM(32));

VALUE m_NameRefFlags = rb_define_module_under(m_clang,"NameRefFlags");
rb_define_const(m_NameRefFlags,"WantQualifier", INT2NUM(1));
rb_define_const(m_NameRefFlags,"WantTemplateArgs", INT2NUM(2));
rb_define_const(m_NameRefFlags,"WantSinglePiece", INT2NUM(4));

VALUE m_TokenKind = rb_define_module_under(m_clang,"TokenKind");
rb_define_const(m_TokenKind,"Punctuation", INT2NUM(0));
rb_define_const(m_TokenKind,"Keyword", INT2NUM(1));
rb_define_const(m_TokenKind,"Identifier", INT2NUM(2));
rb_define_const(m_TokenKind,"Literal", INT2NUM(3));
rb_define_const(m_TokenKind,"Comment", INT2NUM(4));

VALUE m_CompletionChunkKind = rb_define_module_under(m_clang,"CompletionChunkKind");
rb_define_const(m_CompletionChunkKind,"Optional", INT2NUM(0));
rb_define_const(m_CompletionChunkKind,"TypedText", INT2NUM(1));
rb_define_const(m_CompletionChunkKind,"Text", INT2NUM(2));
rb_define_const(m_CompletionChunkKind,"Placeholder", INT2NUM(3));
rb_define_const(m_CompletionChunkKind,"Informative", INT2NUM(4));
rb_define_const(m_CompletionChunkKind,"CurrentParameter", INT2NUM(5));
rb_define_const(m_CompletionChunkKind,"LeftParen", INT2NUM(6));
rb_define_const(m_CompletionChunkKind,"RightParen", INT2NUM(7));
rb_define_const(m_CompletionChunkKind,"LeftBracket", INT2NUM(8));
rb_define_const(m_CompletionChunkKind,"RightBracket", INT2NUM(9));
rb_define_const(m_CompletionChunkKind,"LeftBrace", INT2NUM(10));
rb_define_const(m_CompletionChunkKind,"RightBrace", INT2NUM(11));
rb_define_const(m_CompletionChunkKind,"LeftAngle", INT2NUM(12));
rb_define_const(m_CompletionChunkKind,"RightAngle", INT2NUM(13));
rb_define_const(m_CompletionChunkKind,"Comma", INT2NUM(14));
rb_define_const(m_CompletionChunkKind,"ResultType", INT2NUM(15));
rb_define_const(m_CompletionChunkKind,"Colon", INT2NUM(16));
rb_define_const(m_CompletionChunkKind,"SemiColon", INT2NUM(17));
rb_define_const(m_CompletionChunkKind,"Equal", INT2NUM(18));
rb_define_const(m_CompletionChunkKind,"HorizontalSpace", INT2NUM(19));
rb_define_const(m_CompletionChunkKind,"VerticalSpace", INT2NUM(20));

VALUE m_CodeComplete_Flags = rb_define_module_under(m_clang,"CodeComplete_Flags");
rb_define_const(m_CodeComplete_Flags,"IncludeMacros", INT2NUM(1));
rb_define_const(m_CodeComplete_Flags,"IncludeCodePatterns", INT2NUM(2));
rb_define_const(m_CodeComplete_Flags,"IncludeBriefComments", INT2NUM(4));

VALUE m_CompletionContext = rb_define_module_under(m_clang,"CompletionContext");
rb_define_const(m_CompletionContext,"Unexposed", INT2NUM(0));
rb_define_const(m_CompletionContext,"AnyType", INT2NUM(1));
rb_define_const(m_CompletionContext,"AnyValue", INT2NUM(2));
rb_define_const(m_CompletionContext,"ObjCObjectValue", INT2NUM(4));
rb_define_const(m_CompletionContext,"ObjCSelectorValue", INT2NUM(8));
rb_define_const(m_CompletionContext,"CXXClassTypeValue", INT2NUM(16));
rb_define_const(m_CompletionContext,"DotMemberAccess", INT2NUM(32));
rb_define_const(m_CompletionContext,"ArrowMemberAccess", INT2NUM(64));
rb_define_const(m_CompletionContext,"ObjCPropertyAccess", INT2NUM(128));
rb_define_const(m_CompletionContext,"EnumTag", INT2NUM(256));
rb_define_const(m_CompletionContext,"UnionTag", INT2NUM(512));
rb_define_const(m_CompletionContext,"StructTag", INT2NUM(1024));
rb_define_const(m_CompletionContext,"ClassTag", INT2NUM(2048));
rb_define_const(m_CompletionContext,"Namespace", INT2NUM(4096));
rb_define_const(m_CompletionContext,"NestedNameSpecifier", INT2NUM(8192));
rb_define_const(m_CompletionContext,"ObjCInterface", INT2NUM(16384));
rb_define_const(m_CompletionContext,"ObjCProtocol", INT2NUM(32768));
rb_define_const(m_CompletionContext,"ObjCCategory", INT2NUM(65536));
rb_define_const(m_CompletionContext,"ObjCInstanceMessage", INT2NUM(131072));
rb_define_const(m_CompletionContext,"ObjCClassMessage", INT2NUM(262144));
rb_define_const(m_CompletionContext,"ObjCSelectorName", INT2NUM(524288));
rb_define_const(m_CompletionContext,"MacroName", INT2NUM(1048576));
rb_define_const(m_CompletionContext,"NaturalLanguage", INT2NUM(2097152));
rb_define_const(m_CompletionContext,"Unknown", INT2NUM(4194303));

VALUE m_VisitorResult = rb_define_module_under(m_clang,"VisitorResult");
rb_define_const(m_VisitorResult,"Break", INT2NUM(0));
rb_define_const(m_VisitorResult,"Continue", INT2NUM(1));

VALUE m_Result = rb_define_module_under(m_clang,"Result");
rb_define_const(m_Result,"Success", INT2NUM(0));
rb_define_const(m_Result,"Invalid", INT2NUM(1));
rb_define_const(m_Result,"VisitBreak", INT2NUM(2));

VALUE m_IdxEntityKind = rb_define_module_under(m_clang,"IdxEntityKind");
rb_define_const(m_IdxEntityKind,"Unexposed", INT2NUM(0));
rb_define_const(m_IdxEntityKind,"Typedef", INT2NUM(1));
rb_define_const(m_IdxEntityKind,"Function", INT2NUM(2));
rb_define_const(m_IdxEntityKind,"Variable", INT2NUM(3));
rb_define_const(m_IdxEntityKind,"Field", INT2NUM(4));
rb_define_const(m_IdxEntityKind,"EnumConstant", INT2NUM(5));
rb_define_const(m_IdxEntityKind,"ObjCClass", INT2NUM(6));
rb_define_const(m_IdxEntityKind,"ObjCProtocol", INT2NUM(7));
rb_define_const(m_IdxEntityKind,"ObjCCategory", INT2NUM(8));
rb_define_const(m_IdxEntityKind,"ObjCInstanceMethod", INT2NUM(9));
rb_define_const(m_IdxEntityKind,"ObjCClassMethod", INT2NUM(10));
rb_define_const(m_IdxEntityKind,"ObjCProperty", INT2NUM(11));
rb_define_const(m_IdxEntityKind,"ObjCIvar", INT2NUM(12));
rb_define_const(m_IdxEntityKind,"Enum", INT2NUM(13));
rb_define_const(m_IdxEntityKind,"Struct", INT2NUM(14));
rb_define_const(m_IdxEntityKind,"Union", INT2NUM(15));
rb_define_const(m_IdxEntityKind,"CXXClass", INT2NUM(16));
rb_define_const(m_IdxEntityKind,"CXXNamespace", INT2NUM(17));
rb_define_const(m_IdxEntityKind,"CXXNamespaceAlias", INT2NUM(18));
rb_define_const(m_IdxEntityKind,"CXXStaticVariable", INT2NUM(19));
rb_define_const(m_IdxEntityKind,"CXXStaticMethod", INT2NUM(20));
rb_define_const(m_IdxEntityKind,"CXXInstanceMethod", INT2NUM(21));
rb_define_const(m_IdxEntityKind,"CXXConstructor", INT2NUM(22));
rb_define_const(m_IdxEntityKind,"CXXDestructor", INT2NUM(23));
rb_define_const(m_IdxEntityKind,"CXXConversionFunction", INT2NUM(24));
rb_define_const(m_IdxEntityKind,"CXXTypeAlias", INT2NUM(25));
rb_define_const(m_IdxEntityKind,"CXXInterface", INT2NUM(26));

VALUE m_IdxEntityLanguage = rb_define_module_under(m_clang,"IdxEntityLanguage");
rb_define_const(m_IdxEntityLanguage,"None", INT2NUM(0));
rb_define_const(m_IdxEntityLanguage,"C", INT2NUM(1));
rb_define_const(m_IdxEntityLanguage,"ObjC", INT2NUM(2));
rb_define_const(m_IdxEntityLanguage,"CXX", INT2NUM(3));

VALUE m_IdxEntityXTemplateKind = rb_define_module_under(m_clang,"IdxEntityXTemplateKind");
rb_define_const(m_IdxEntityXTemplateKind,"NonTemplate", INT2NUM(0));
rb_define_const(m_IdxEntityXTemplateKind,"Template", INT2NUM(1));
rb_define_const(m_IdxEntityXTemplateKind,"TemplatePartialSpecialization", INT2NUM(2));
rb_define_const(m_IdxEntityXTemplateKind,"TemplateSpecialization", INT2NUM(3));

VALUE m_IdxAttrKind = rb_define_module_under(m_clang,"IdxAttrKind");
rb_define_const(m_IdxAttrKind,"Unexposed", INT2NUM(0));
rb_define_const(m_IdxAttrKind,"IBAction", INT2NUM(1));
rb_define_const(m_IdxAttrKind,"IBOutlet", INT2NUM(2));
rb_define_const(m_IdxAttrKind,"IBOutletCollection", INT2NUM(3));

VALUE m_IdxDeclInfoFlags = rb_define_module_under(m_clang,"IdxDeclInfoFlags");
rb_define_const(m_IdxDeclInfoFlags,"Skipped", INT2NUM(1));

VALUE m_IdxObjCContainerKind = rb_define_module_under(m_clang,"IdxObjCContainerKind");
rb_define_const(m_IdxObjCContainerKind,"ForwardRef", INT2NUM(0));
rb_define_const(m_IdxObjCContainerKind,"Interface", INT2NUM(1));
rb_define_const(m_IdxObjCContainerKind,"Implementation", INT2NUM(2));

VALUE m_IdxEntityRefKind = rb_define_module_under(m_clang,"IdxEntityRefKind");
rb_define_const(m_IdxEntityRefKind,"Direct", INT2NUM(1));
rb_define_const(m_IdxEntityRefKind,"Implicit", INT2NUM(2));

VALUE m_IndexOptFlags = rb_define_module_under(m_clang,"IndexOptFlags");
rb_define_const(m_IndexOptFlags,"None", INT2NUM(0));
rb_define_const(m_IndexOptFlags,"SuppressRedundantRefs", INT2NUM(1));
rb_define_const(m_IndexOptFlags,"IndexFunctionLocalSymbols", INT2NUM(2));
rb_define_const(m_IndexOptFlags,"IndexImplicitTemplateInstantiations", INT2NUM(4));
rb_define_const(m_IndexOptFlags,"SuppressWarnings", INT2NUM(8));
rb_define_const(m_IndexOptFlags,"SkipParsedBodiesInSession", INT2NUM(16));

