#sudo: required
#dist: trusty
#
#rvm:
#  - 2.1
#  - 2.2
#  - 2.3.0
#  - ruby-head
#

#./tools/travis_install.sh
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      rvm:
        - 2.1
        - 2.2
        - 2.3.0
        - ruby-head
      addons:
        apt:
          packages: 
          - llvm-dev
          - libclang-3.5-dev
          - libclang1-3.5 
          - libclang-common-3.5-dev 
          - build-essential 
          - ruby-dev
      env: CLANG_SRC_VER=3.5

#    - os: linux
#      compiler: clang
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
#          packages: ['clang-3.6','libclang-3.5-dev']
#      env: COMPILER=clang++-3.6
#script: CXX=$COMPILER ./tools/reinstallgem.sh

before_install:
  - sudo apt-get update -qq
    #  - sudo apt-get install -qq llvm-dev libclang-3.5-dev libclang1-3.5 libclang-common-3.5-dev build-essential ruby-dev
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libclang-3.5.so /usr/lib/x86_64-linux-gnu/libclang.so
  - gem install bundler

script: 
  - bundle exec tools/build_gem.sh
  - bundle exec gem install --debug --verbose --local clangc-0.0.1.gem
  - ./tools/run_tests.sh
